print("Twinkle,Twinkle,LITTLE star,")
print("How are wonder what you are ")
print("up above the world so high ")
print("like a dimond in the sky ")
print("Twinkle,Twinkle,LITTLE star,")
print("How are wonder what you are ")
print("up above the world so high ")
print("like a dimond in the sky ")
print("Twinkle,Twinkle,LITTLE star,")
print("How are wonder what you are ")
print("up above the world so high ")
print("like a dimond in the sky ")
print("(winkle,Twinkle,LITTLE star,")
print("How are wonder what you are ")
print("up above the world so high ")
print("like a dimond in the sky ")
