f=open("write.txt", "a")
f.write("\nyou can do anything and I have trust on myself that definetly I get out my father and mother from this trauma \n")
f.write("\nyou can do anything and I have trust on myself that definetly I get out my father and mother from this trauma \n")
f.write("\nyou can do anything and I have trust on myself that definetly I get out my father and mother from this trauma \n")
f.write("\nyou can do anything and I have trust on myself that definetly I get out my father and mother from this trauma \n")
f.close()